<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Kata Sandi harus diisi</name>
   <tag></tag>
   <elementGuidId>72e8d6f2-b756-46ac-adac-8a77878b6124</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#warning-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;warning-password&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>04a456b5-4903-464d-904b-4881ee18c22d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>warning-password show</value>
      <webElementGuid>3f46fbbb-8728-4d28-a581-54965c1c4a95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>warning-password</value>
      <webElementGuid>2ce62ecd-67f2-429e-8abc-e82ca145d64c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Kata Sandi harus diisi</value>
      <webElementGuid>a55e9345-3b09-4d79-9bea-19fece5fdd9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;warning-password&quot;)</value>
      <webElementGuid>89ddb461-b810-4eeb-8809-678963298ec0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='warning-password']</value>
      <webElementGuid>f61c0bf5-92a5-47bd-932f-9b51d188c1ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='step-4']/div/div/div[2]/div/div[3]/div[3]</value>
      <webElementGuid>3c4d0280-2215-454d-8379-fd59c5c59ed9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kata Sandi'])[1]/following::div[3]</value>
      <webElementGuid>ab064355-d2f7-40a9-b47e-00fce8b4b7b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nomor Handphone harus diisi'])[1]/following::div[5]</value>
      <webElementGuid>31b3320a-7e91-40a0-a4a3-8b3d095dc2eb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lupa Kata Sandi'])[1]/preceding::div[1]</value>
      <webElementGuid>353dafc8-3414-476b-a1c2-227b465e24e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Masuk'])[2]/preceding::div[3]</value>
      <webElementGuid>90b47202-3a2f-4eed-9774-dfc4c13f2163</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Kata Sandi harus diisi']/parent::*</value>
      <webElementGuid>8fb6a91b-2d1b-435c-b134-534c8fc2087e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[3]</value>
      <webElementGuid>ec349c44-6c1a-4ca4-8ce5-981d13bd0fc1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'warning-password' and (text() = 'Kata Sandi harus diisi' or . = 'Kata Sandi harus diisi')]</value>
      <webElementGuid>a1ca33bf-9a11-43d6-8641-74cbed939da4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='No Handphone'])[1]/following::div[6]</value>
      <webElementGuid>572f7463-3cf6-4fa3-a730-0be2994f37bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
