<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aktifkan Semua Cookie</name>
   <tag></tag>
   <elementGuidId>8ef39372-867b-4231-91d0-63c6ba83d94e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#footer_tc_privacy_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='footer_tc_privacy_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>4570f577-9a5b-47b8-884d-cc0cdd5af422</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>footer_tc_privacy_button</value>
      <webElementGuid>d24f8c6a-85e1-4a49-916f-707137219759</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tc-reset-css tc-privacy-button</value>
      <webElementGuid>aadf05ca-3493-48ca-98ad-ba16a71faa9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>eb986753-5fcf-40be-a723-b4b5a18e99bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aktifkan Semua Cookie</value>
      <webElementGuid>a14ee3ba-1981-413a-bc0b-9189362b962d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aktifkan Semua Cookie</value>
      <webElementGuid>6ebb72ac-31f6-4d32-b605-9e2db9f57a63</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer_tc_privacy_button&quot;)</value>
      <webElementGuid>4707c910-f4fc-43d5-8e3d-ca2d69db2489</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='footer_tc_privacy_button']</value>
      <webElementGuid>64ee48f2-3239-4c99-81d1-bac07d1f0d69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footer_tc_privacy_container_button']/button[2]</value>
      <webElementGuid>c766056e-11e6-4949-bcce-e5be65581f43</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengaturan Cookie'])[1]/following::button[1]</value>
      <webElementGuid>c55c5372-5e46-417f-861e-5d92e1715303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kontak kami'])[2]/following::button[2]</value>
      <webElementGuid>cc6dbdde-df7a-4dfb-96ef-36f90ce2160f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aktifkan Semua Cookie']/parent::*</value>
      <webElementGuid>736e7c6b-970f-416e-9162-6baa6cf13428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/button[2]</value>
      <webElementGuid>261f1f23-186c-4b54-be44-21208b54fe89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'footer_tc_privacy_button' and @type = 'button' and @title = 'Aktifkan Semua Cookie' and (text() = 'Aktifkan Semua Cookie' or . = 'Aktifkan Semua Cookie')]</value>
      <webElementGuid>df039798-b63e-4dec-8942-f38bd6519271</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
