<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Aktifkan Semua Cookie</name>
   <tag></tag>
   <elementGuidId>8ef39372-867b-4231-91d0-63c6ba83d94e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#footer_tc_privacy_button</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='footer_tc_privacy_button']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>d98c1526-c4e2-4bb4-a654-efe969ca4181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>footer_tc_privacy_button</value>
      <webElementGuid>d750cdf0-ebea-483f-843a-95309d937cff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tc-reset-css tc-privacy-button</value>
      <webElementGuid>3522d938-b583-40ce-88aa-67d4effd1f33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>86e56bb5-1e78-48e0-b24f-a882dbeae36c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Aktifkan Semua Cookie</value>
      <webElementGuid>8e7daa90-7be6-4f85-9f7a-975b46632a03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Aktifkan Semua Cookie</value>
      <webElementGuid>1e937b08-816d-4a53-ac05-c8a06039ef1f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;footer_tc_privacy_button&quot;)</value>
      <webElementGuid>bfa0c5bb-d408-49d5-ac1d-5f79d3c95282</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='footer_tc_privacy_button']</value>
      <webElementGuid>4907fb63-1897-4343-9319-9d7646bcf8f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='footer_tc_privacy_container_button']/button[2]</value>
      <webElementGuid>daf5bf11-1af7-44a6-8e25-c7ea6b4332fa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pengaturan Cookie'])[1]/following::button[1]</value>
      <webElementGuid>df656438-9379-4c7b-bb23-7401e39a5723</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='kontak kami'])[2]/following::button[2]</value>
      <webElementGuid>303e7002-be85-4c1b-99bf-156de888488e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Aktifkan Semua Cookie']/parent::*</value>
      <webElementGuid>4dd6fd25-a879-4e94-a29c-c9496a697d92</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/div/div[2]/button[2]</value>
      <webElementGuid>9bde5140-e361-43bc-b953-3a20b1549ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'footer_tc_privacy_button' and @type = 'button' and @title = 'Aktifkan Semua Cookie' and (text() = 'Aktifkan Semua Cookie' or . = 'Aktifkan Semua Cookie')]</value>
      <webElementGuid>e1e1c10c-a643-40a1-b5b0-73de1421168d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
