<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Daftar___st_preview_frame_bpn</name>
   <tag></tag>
   <elementGuidId>cebe0bbe-6341-472a-9a37-2a3790c6fada</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>iframe.__st_preview_frame_bpn</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='__st_fancy_popup']/iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>95616d44-d05e-4158-9fc1-8da523da8c38</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>__st_preview_frame_bpn</value>
      <webElementGuid>6787f593-238c-4f2a-8f6b-2a27d11a3165</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>15723e2f-9176-46f4-b53e-52705ec57181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>e55d0943-f1d7-43d9-a96f-7eb02aeb6bd0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;__st_fancy_popup&quot;)/iframe[@class=&quot;__st_preview_frame_bpn&quot;]</value>
      <webElementGuid>eb451eba-dedb-4f38-b52c-27cbf58e6dab</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__st_fancy_popup']/iframe</value>
      <webElementGuid>224bd4b9-ec8a-44fd-975d-a67cb85cd110</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[9]/iframe</value>
      <webElementGuid>5aa91fdf-4638-42e8-a42d-f9d134ca1849</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
